"""empty message

Revision ID: 088c649e83cb
Revises: f0e9d66fbf10
Create Date: 2023-07-24 08:55:05.785116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088c649e83cb'
down_revision = 'f0e9d66fbf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
